"""Markers for auto-injected sections in markdown files."""

# SYSTEM-INDEX.md sections
DOMAINS_MARKER_START = "<!-- BEGIN LIFE DOMAINS -->"
DOMAINS_MARKER_END = "<!-- END LIFE DOMAINS -->"
CUSTOM_APPS_MARKER_START = "<!-- BEGIN CUSTOM APPS -->"
CUSTOM_APPS_MARKER_END = "<!-- END CUSTOM APPS -->"
GUIDES_MARKER_START = "<!-- BEGIN GUIDES -->"
GUIDES_MARKER_END = "<!-- END GUIDES -->"
SYSTEM_SPECS_MARKER_START = "<!-- BEGIN SYSTEM SPECS -->"
SYSTEM_SPECS_MARKER_END = "<!-- END SYSTEM SPECS -->"
ROLES_MARKER_START = "<!-- BEGIN ROLES -->"
ROLES_MARKER_END = "<!-- END ROLES -->"
MISSIONS_MARKER_START = "<!-- BEGIN MISSIONS -->"
MISSIONS_MARKER_END = "<!-- END MISSIONS -->"

# TODAY.md sections
CALENDAR_MARKER_START = "<!-- BEGIN CALENDAR -->"
CALENDAR_MARKER_END = "<!-- END CALENDAR -->"
PRIORITIES_MARKER_START = "<!-- BEGIN PRIORITIES -->"
PRIORITIES_MARKER_END = "<!-- END PRIORITIES -->"
