-- Calendar App Schema (Direct-Read Apple Calendar)
--
-- Data-plane reads come from Apple Calendar SQLite (read-only).
-- System DB stores only preferences.
-- No cache tables, no sync state.
--
-- NOTE: calendar_accounts and calendar_settings tables have been removed.
-- Account configuration is now in the unified 'accounts' table.
-- Calendar preferences are now in the unified 'settings' table.
-- See migrations 035, 036 for the migration path.

-- =============================================================================
-- NOTE: All tables removed (unified accounts pattern)
-- =============================================================================
-- REMOVED: calendar_accounts (moved to unified accounts table)
-- REMOVED: calendar_settings (moved to unified settings table)
-- REMOVED: calendar_calendars (direct-read from Apple DB)
-- REMOVED: calendar_events (direct-read from Apple DB)
--
-- Calendar preferences are now in the settings table with keys:
--   - default_calendar
--   - default_meeting_calendar
--   - default_personal_calendar
